### ISSUE TITLE
What is the result on the bird dataset with GPT-3.5-turbo

### ISSUE THREAD

**Issue by 545999961** [BeachWang/DAIL-SQL#26]
I would like to understand the performance of DIAL-SQL on the bird dataset under GPT-3.5-turbo. May I ask if you have any results?

**Comment by BeachWang** [comment]
Hi,

Thank you for your interest in our work. We have not yet tested the performance of DAIL-SQL on the bird dataset under GPT-3.5-turbo.

**Comment by 545999961** [comment]
Okay, I'd like to know how much budget would be required to run validation tests on the Spider dataset and Bird dataset using DAIL-SQL with GPT-4.

**Comment by BeachWang** [comment]
Hi,

You can refer to Appendix E.1 in our [updated paper](https://arxiv.org/pdf/2308.15363.pdf). There are detail analyses of financial efficiency of DAIL-SQL without self-consistency in Spider-Dev at November 8, 2023. BTY, the self-consistency does not increase the cost much since only the output tokens are duplicately included in the cost. The evaluation on Bird costs at the same level.

**Comment by 545999961** [comment]
OK. Thanks!
