### ISSUE TITLE
Detailed README

### ISSUE THREAD

**Issue by SonuGupta00sg** [BeachWang/DAIL-SQL#3]
Hello, I just read your paper and am looking at the code. I appreciate your efforts for this new method. I want to use this method on my database and I am not getting it after reading this how can I do this or it is just for spider data?  I would be grateful if you could guide us on how can we use on own data.
Thanks !!

**Comment by BeachWang** [comment]
Hi,

Thank you for expressing your interest. We apologize for the inconvenience, as the provided code is specifically designed for Spider data and may require additional efforts for adapting it to a Text2SQL assistant. However, if you wish to apply it to your own database, we can offer some suggestions. Since our solution is a few-shot approach, it requires example candidates. In this case, you can utilize the Spider train data as the candidate pool. Additionally, for application purposes, using the Masked Question Similarity Selection should suffice. You may need to create your own `utils/linking_process.py` function to facilitate this process.
